### PR TITLE
Add `sshOpts` option, default to empty SSH options

### PR DESCRIPTION
**Pull request by sorki**
Coincidentally both options break my use-case as I do use `ControlPath/ControlMaster` and usually log-in to machines on another console so I just expect other SSH based tools to just work without entering key again.

As I currently don't use SSH agent, `BatchMode` seems to prevent key password prompt which is bad especiall with the combination of the former option.

This makes SSH options configurable and less opinionated as this is quite common source of trouble. Personally I think it's better to manage SSH hosts and their required options via `ssh_config`, possibly with `home-manager`.

### CODE REVIEW

**Comment by Infinisil** [comment]
Getting rid of `BatchMode` seems fine, but I initially added `ControPath=none` so that it explicitly *wouldn't* use previous connections when attempting to verify whether a machine started successfully. This is such that even if you break your SSH setup, it could still detect that, and do a roll back. Afaik this can't be done if it uses an existing connection.

**Comment by sorki** [comment]
Ah, makes sense. I think removing `BatchMode` so SSH asks for passphrase is enough to fix my use-case. Would you prefer to still have `sshOpts` option or just removal of `BatchMode`?

**Comment by infinisil** [comment]
I removed most SSH options now in https://github.com/infinisil/nixus/commit/aa276744ba7dcebeac40da37d7bf4d9d5409f17e, I guess this should work for you?

**Comment by sorki** [comment]
Yep, looks good. Thanks!

**Pull request closed without merging**
